- name: Ensure application is deployed
  hosts: prod
  become: true
  vars_files:
    - "files/secrets/devops.yml"
  tasks:
    - block:
        - name: Check that you can connect to webpage
          uri:
            url: http://3.91.242.173
          retries: 8
          delay: 5

        - name: Check webservice application production
          uri:
            url: http://3.91.242.173/health
            method: GET
          retries: 8
          delay: 5
      tags:
        - prod
